### ISSUE TITLE
gfx1150 (Radeon 890M) Segmentation Fault on Linux

### ISSUE THREAD

**Issue by iz0eyj** [lemonade-sdk/llamacpp-rocm#51]
### Description

On my Windows 11 setup, `llamacpp-rocm` can load and run Qwen3 30B 8‑bit models (and even larger ones) without issues, with all layers offloaded to the GPU and long context lengths (e.g. 32k).

On the same machine running Debian 13 with ROCm, the **same model** fails to load on GPU with ROCm OOM errors, and for some settings even ends with a **segmentation fault**, despite ROCm reporting more than 50 GB of visible VRAM available.

From my point of view this looks like a bug in the ROCm backend or its error handling:
- Windows 11 + `llamacpp-rocm` on this hardware can load 30B / 40B 8‑bit models and run them with all layers on GPU.
- Debian 13 + ROCm on the same hardware fails to allocate a ~30–32 GB ROCm buffer and, in some cases, segfaults right after an OOM from `cudaMalloc`/HIP.

---

### Hardware

- CPU / APU: AMD Ryzen AI 9 HX370
- GPU: integrated AMD Radeon 890M (gfx1150)
- RAM: 96 GB system RAM
- BIOS: 48 GB UMA / shared memory assigned **statically** to the iGPU
- Cooling / clocks: standard, nothing exotic

---

### OS and Drivers

- OS: Debian 13 (amd64)
- Kernel: (will provide with `uname -r`)
- ROCm: installed from Debian/ROCm packages (will provide exact versions with `apt policy`)

ROCm seems to see the expected amount of visible VRAM:

```bash
$ rocm-smi --showmeminfo vram --showmeminfo vis_vram --showuse

================================== Memory Usage (Bytes) ==================================
GPU[0]          : VIS_VRAM Total Memory (B): 51539607552
GPU[0]          : VIS_VRAM Total Used Memory (B): 151011328
==========================================================================================
```

So roughly 51.5 GB of VIS_VRAM total, with ~151 MB used.

`llama.cpp` reports:

```text
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon 890M Graphics, gfx1150 (0x1150), VMM: no, Wave Size: 32
```

Note: `VMM: no` might be relevant here.

---

### llama.cpp / llamacpp-rocm

- llamacpp-rocm build: (will provide `./llama-cli --version` output)
  Example from my test:
  ```text
  build      : b1-8f91ca5
  ```

- Built with ROCm backend on Debian 13.

---

### Model

- Model family: Qwen3‑VL‑30B, 8‑bit GGUF
- Format: GGUF, 8‑bit quantization
- Path in my setup: `/mnt/sda/Models/Qwen3/VL/model.gguf`

On Windows 11 with the same hardware and llamacpp‑rocm, this model loads and runs with all layers on GPU and long context (e.g. 32k) without any visible issues.

---

### Reproducer 1: OOM when loading full model

Command:

```bash
./llama-cli \
  --no-mmap \
  -c 32768 \
  -m /mnt/sda/Models/Qwen3/VL/model.gguf
```

Output (relevant part):

```text
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon 890M Graphics, gfx1150 (0x1150), VMM: no, Wave Size: 32

Loading model... |ggml_backend_cuda_buffer_type_alloc_buffer: allocating 30658,12 MiB on device 0: cudaMalloc failed: out of memory
alloc_tensor_range: failed to allocate ROCm0 buffer of size 32147367936
llama_model_load: error loading model: unable to allocate ROCm0 buffer
llama_model_load_from_file_impl: failed to load model
common_init_from_params: failed to load model '/mnt/sda/Models/Qwen3/VL/model.gguf'
srv    load_model: failed to load model, '/mnt/sda/Models/Qwen3/VL/model.gguf'

Failed to load the model
```

So `cudaMalloc`/HIP fails for a ~30 GB allocation on ROCm, although `rocm-smi` reports ~51.5 GB of VIS_VRAM and only ~151 MB used.

On Windows 11 (same machine, same BIOS UMA, same model) this configuration loads fine and I can run at about ~22 tokens/s generation at empty context.

---

### Reproducer 2: OOM for smaller buffer, then segmentation fault

If I try to partially offload layers to GPU with `-ngl`, I hit another problem: first an OOM for a buffer of ~2.3 GB, then **segmentation fault**.

Command:

```bash
./llama-cli \
  --no-mmap \
  -ngl 37 \
  -c 32768 \
  -m /mnt/sda/Models/Qwen3/VL/model.gguf
```

Output:

```text
ggml_cuda_init: found 1 ROCm devices:
  Device 0: AMD Radeon 890M Graphics, gfx1150 (0x1150), VMM: no, Wave Size: 32

Loading model... |ggml_backend_cuda_buffer_type_alloc_buffer: allocating 2304,00 MiB on device 0: cudaMalloc failed: out of memory
alloc_tensor_range: failed to allocate ROCm0 buffer of size 2415919104
Errore di segmentazione
```

So:

1. `cudaMalloc` (HIP) fails allocating ~2.3 GB, which is surprising given the amount of VIS_VRAM reported as free.
2. After this OOM, the process crashes with a segmentation fault instead of cleanly aborting with an error.

This second part (segfault) looks like a clear bug in error handling in the ROCm backend or in the way llama.cpp reacts to failed allocations.

---

### Expected behavior

- If ROCm cannot allocate the required buffers, `llama-cli` should fail cleanly with an error (no segmentation fault).
- Given that the same model and hardware can be fully loaded and used on Windows 11 (llamacpp‑rocm build), I would expect the ROCm backend on Linux to either:
  - handle large allocations correctly on this APU (gfx1150, UMA 48 GB), or
  - fail in a documented and stable way, not with inconsistent OOMs and segfaults.

---

### Actual behavior

- On Debian 13 + ROCm on Ryzen AI 9 HX370:
  - Loading Qwen3‑VL‑30B 8‑bit with full GPU offload and 32k context fails with OOM on a ~30 GB ROCm buffer, despite ~51.5 GB VIS_VRAM being reported free.
  - Attempting to use `-ngl 37` (partial offload) leads to:
    - OOM for a ~2.3 GB buffer.
    - Immediate **segmentation fault** right after the OOM.

- On Windows 11 (same machine, same BIOS settings, llamacpp‑rocm build):
  - Qwen3‑VL‑30B 8‑bit loads successfully.
  - Even larger 8‑bit models (40B class) can be loaded and run with all layers on GPU.
  - With empty context, this Qwen3 30B model runs at ~22 tokens/s generation.

---

### Notes / related issues

- This looks similar in spirit to:
  - ROCm/HIP `hipMalloc` failing even though there is enough memory, because of fragmentation or allocation constraints.
  - llama.cpp ROCm‑related regressions / OOM behavior differences on recent ROCm/llama.cpp versions.

- Given the symptoms, there might be two problems:
  1. ROCm backend (HIP) refusing large allocations on this APU even with plenty of VIS_VRAM available.
  2. llama.cpp ROCm backend not handling the failed allocation path robustly and segfaulting.

If you need, I can provide:
- Full `./llama-cli --version` output.
- `uname -r`.
- `apt policy` for ROCm packages.
- `gdb`/`coredumpctl` backtrace for the segmentation fault.

**Comment by benrichard-amd** [comment]
Hi @iz0eyj 

Thanks for the logs. I'm trying to get a machine where I can reproduce this. In the meantime can you provide more informations so I can create the same setup:

kernel version: `uname -r`

ROCm version and install method.

**Comment by benrichard-amd** [comment]
Hi @iz0eyj 

I think I see what's going on here. Seems to be a common issue.

Try setting `ttm.pages_limit=12582912` to your kernel arguments. (48GB / 4KB pages = 12582912 pages).

There are a few ways you can do this:

**Temporary (does not persist across reboots):**

1. At the GRUB boot menu, highlight the OS you want to boot and press `e` for edit. 

2. Edit the `linux` line so it looks something like,

`/boot/vmlinuz-6.12.63+deb13-amd64 root=UUID=c6984030-26b2-4d77-938b-f2fdbdd9c0c1 ro quiet ttm.pages_limit=12582912`

3. Then press `CTRL + X` to save and exit.

**Permanent:**

1. As root open `/etc/default/grub` 

2. Edit the `GRUB_CMDLINE_LINUX_DEFAULT` variable to include `ttm.pages_limit=12582912`:

`GRUB_CMDLINE_LINUX_DEFAULT="quiet ttm.pages_limit=12582912"`

3. Run `update-grub` and reboot


**Use the AMD ttm tool**

We also have a tool for this. But I tried it on Debian and the changes did not take effect: https://rocm.docs.amd.com/projects/radeon-ryzen/en/latest/docs/install/installryz/native_linux/install-ryzen.html#configure-shared-memory

Let me know if you need any help.

Thanks.

**Comment by iz0eyj** [comment]
@benrichard-amd 
Quick update: after setting ttm.pages_limit=12582912 as you suggested, Qwen3 VL 30B A3B Q8_0 now loads and runs fine with ROCm on my gfx1150 APU with 48 GiB UMA VRAM. The ~30 GiB ROCm buffer is allocated successfully and there is no longer any cudaMalloc failed: out of memory error. Thank you for the hint about the TTM page limit, that solved the Linux side for me.
For completeness: on this same machine, the Vulkan backend of upstream llama.cpp is still slightly faster in tokens/sec and seems to degrade a bit less when the context grows, but now ROCm is at least fully usable for 30B 8‑bit models on Linux as well.

llama-server \
  -c 16384 \
  --batch-size 8192 \
  --ubatch-size 2048 \
  --context-shift \
  -ngl 999 \
  --parallel 4 \
  --flash-attn \
  -m /var/models/Qwen3/VL/model.gguf

If you need me to run any additional tests or try different ROCm/kernel settings on this machine, I’m happy to help. This system is dedicated to local LLMs, so I can schedule more experiments if that’s useful.


One more, more general question related to this platform:
given that Ryzen AI 300 / gfx1150 systems have a fairly capable NPU on‑die, is there any plan on the AMD / llama.cpp side to support running medium‑sized 8 bit LLMs (e.g. 3–8B, or selected layers of 14–30B) on the NPU, either via the official Ryzen AI Software stack (ONNX Runtime / EP) or other documented APIs?
Right now the GPU path with ROCm works for 30B 8‑bit after tuning TTM as above, but the NPU remains unused on Linux even though it would be a very interesting target for smaller and mixed CPU+NPU deployments.

Thank you, Federico.
